### ISSUE TITLE
How do I install rerun ?

### ISSUE THREAD

**Issue by ggrossetie** [jgaskins/clearwater_ruby_benchmarks#1]
`dev` script file is using `rerun` command:

```bash
(bundle check || bundle) && rerun -i 'assets/**/*' 'rackup -p 3000'
```
Do I need to install https://rerun.github.io/rerun/ ?

**Comment by jgaskins** [comment]
Ah, yep. Sorry, I didn't even think about that. It could be run with just the `rackup` command and the changes in the client code will be picked up automatically, but using `rerun` lets me make changes to the server code and it will reload the app.

I use it on all my non-Rails apps, mainly because I don't know of any other server-side reloaders. :-)

**Comment by ggrossetie** [comment]
It's fine 😉 
I wasn't 100% sure that I found the correct command line.

> It could be run with just the rackup command

Indeed, I can run the benchmark on my browser with just `rackup -p 3000`  🎉
